### ISSUE TITLE
Volunteers : Paginate & searchable list

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#125]
List of volunteers should be paginated (default 20 rows, possibility to change to 50, 100, all)
and searchable against : first name, last name, mobile, nivol, email. (one search field that search against all those field with a 'OR')

It should be applied in : 
- Volunteer administration
- User Administration
- Volunteers list in a "déclenchement"

this would allow to keep the existing look & feel with the export as PDF button and others at the bottom of the page.

**Comment by ninsuo** [comment]
in the todo list of multi structures (otherwise you should open up 70k volunteers in the same page, does not scale well 😅 )

**Comment by ninsuo** [comment]
the communication status page (volunteer list during a trigger) is very complex and i am not integrating a volunteer search there right now
for the others that's fine/done though

**Comment by ninsuo** [comment]
#123
