### ISSUE TITLE
button should be disabled after clicking on it once

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#126]
- this would avoid the action getting done multiple time
   (and getting the CRSF message which is confusing for non geeky admin for login button)
- the button should be reactivated after 30 seconds.

This principle should be applied to all important button like : 

- ~"Envoyer" un déclenchement~
- CSV/PDF export
- Manual import of all volunteers
- Save volunteer

This button should ask for a confirmation, as it takes long time and consume Pegass API.
- Manual import of all volunteers
  The button is big and can be clicked by mistake on mobile

**Comment by ninsuo** [comment]
Thanks @Dakhtara !
