### ISSUE TITLE
Pegass: attach action structures instead of affiliate structure

### ISSUE THREAD

**Issue by ninsuo** [redcall-io/app#173]
![Screenshot_2020-03-25_at_10_57_21](https://user-images.githubusercontent.com/4152132/77524505-bab0a300-6e87-11ea-89d5-fe316fc4f6ae.png)

When importing someone, its structures are "action structures" and not "affiliate structure".

Warning: for some people, there are no "action structures", so here take the "affiliate structure" by default.

**Comment by mden-crf** [comment]
The user must have the right to emit an alert only for the structure related to his nomination.
Difference between affiliated structure and action structures make no importance in that case. 
It is defined by the following business case : the user is affiliated to the structure which represent his association membership. And the action structures represents the list of all the structure where the user can make some actions (the affiliated structure is very often present in that list too - logic).

Example : 

> **Henry DUNANT**
**Structure de rattachement** : UNITE LOCALE DE LILLE
**Structure(s) d'action** : 
UNITE LOCALE DE LILLE
DT DU NORD
UNITE LOCALE DE MARSEILLE
**Nominations** : 
DLUS - UNITE LOCALE DE LILLE
DLUS.A.MS - UNITE LOCALE DE MARSELLE
PDT - DT DU NORD

In this case, Henry will have the right to emit an alert to : 
- UNITE LOCALE DE LILLE (and all it's child structures) - as he has the DLUS nomination.
- DT DU NORD (and all it's child structures) - as he has the PDT nomination.
