### ISSUE TITLE
Add the ability to format emails

### ISSUE THREAD

**Issue by ninsuo** [redcall-io/app#206]
Currently, emails are written in a simple textarea. 

![Screenshot 2020-04-01 at 13 38 48](https://user-images.githubusercontent.com/4152132/78133113-2d88c380-741e-11ea-9995-15a503baf566.png)

Some people asked if they could format it (using some rich text editor, such as CKEditor?).

![Screenshot 2020-04-01 at 13 40 38](https://user-images.githubusercontent.com/4152132/78133278-704a9b80-741e-11ea-8f3b-f91e54b8f8fc.png)

If you do it, don't forget to sanitize user inputs through purify (https://github.com/Exercise/HTMLPurifierBundle)

**Comment by dev-mansonthomas** [comment]
Tag this as major, since email without formatting are a bit hard to read or emphasis some points.
It has been requested by multiple UL/DT
