### ISSUE TITLE
When a connection issue with pegass is detected, warn end users & disable features

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#249]
Priority should be reconsidered if pegass connexion loss is more frequent

when detecting a communication issue with pegass, display a message to RedCall user that Pegass connection is down and some feature won't be working.

+ When a Pegass is down : maybe it would be good to disable those features.

idea of implementation : 

- Store somewhere a flag (pegass_comm_failure) (DB with in memory table, Firestore for quicker access?) with datetime of the last know failure to communicate.
- retrieve the flag for each page load, and use it to display the appropriate communication and disable impacted features
- the message should stack with user regular communication (added after their message)
- after X minutes of non failure, switch off the flag
- the admin section should allow to switch on & off the flag manually. (and when done manually, automatic switch off shouldn't override)

**Comment by ninsuo** [comment]
Closing this in favor of #377
