### ISSUE TITLE
Pegass Full Sync should be accessible to Dev team only

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#250]
As the feature is used when there's DB change, or when the code that import Pegass have business changes.

So in the Maintenance page of the administration section, this button should be accessible only to developers.
"Synchroniser entièrement la base de données RedCall avec celle de Pegass"

**Comment by ninsuo** [comment]
Modal rendering a warning made by @Dakhtara, thank you 🚀 

We trust our Administrators (otherwise they wouldn't be admin), thus it should be enough.
