### ISSUE TITLE
Fautes d'orthographes

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#297]
Quand on vient de minutis et qu'on a pas les droits RedCall, il manque le premier  "N" a Bienvenu.

Sur la gestion des utilisateurs RedCall, "Ajout d'une entréee" a un e de trop à la fin:
https://redcall.minutis.croix-rouge.fr/admin/pegass/create-user

![image](https://user-images.githubusercontent.com/5695269/81508197-11245480-9303-11ea-8345-a0e8e9ee9d43.png)

**Comment by ninsuo** [comment]
```yaml
  hello_name: 'Bievenue %firstName%,'
  hello_anonymous: 'Bienvene,'
```
joli combo 😅 

corrections effectuées, sera mis en prod en milieu de semaine pro
