### ISSUE TITLE
"relancer la communication" doesn't seems to work when it's an email based communication

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#337]
No Slack notification
No progression indicator
no mail recieved

**Comment by ninsuo** [comment]
Works in development environment 🤔 

<img width="1167" alt="Screenshot 2020-06-26 at 08 30 33" src="https://user-images.githubusercontent.com/4152132/85827874-6b7c5600-b787-11ea-80e7-829494872425.png">

**Comment by ninsuo** [comment]
at least fixed the progress bar

**Comment by ninsuo** [comment]
Ok i think there were some mess between message ids & sent flag
