### ISSUE TITLE
Create Trigger:  offer the ability to trigger by multiple mean

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#339]
Instead of Radio Button, have a checkbox to choose the mean of trigger : call, sms, mail.

When multiple option are checked, sending is done in parallel.
If we should choose an order to send, it would be 

1. call
2. sms
3. mail

If multiple answer are received for the same trigger, the last answer is considered as the valid response.

**Comment by ninsuo** [comment]
Unsure we need to keep this right now.

**Comment by dev-mansonthomas** [comment]
Yes, fallback to SMS for call should do the trick for now
