### ISSUE TITLE
Call Trigger : enable answering machine detection

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#344]
see : https://www.twilio.com/docs/voice/answering-machine-detection

If an answering machine is detected : 
-  read the message to the answering machine
- hang up
- send an SMS
- repeat the call a second time.

**Comment by dev-mansonthomas** [comment]
Currently, if the call is going to voice mail, it leaves a message of about 4 second of silence. 
(on my S10+)

**Comment by dev-mansonthomas** [comment]
Some volunteers do have the message on the answering machine. I did hear the recording on their voice mail (sfr), Bouygues)
However, I tried to reproduce and it didn't work the same way, empty message. (Bouygues)

**Comment by ninsuo** [comment]
I guess it depends on:
- the answering machine welcome message length.
- the length of the message sent by redcall

Currently, RedCall just plays the message when anything picks the call up, so if RedCall message is short or answerphone welcome takes time, there is nothing recorded. In contrary, if RedCall message is long and welcome message is short, you'll have the end of it recorded.

**Comment by ninsuo** [comment]
I may "read the message", but I cannot tell him to press 1 or 2 to answer.

I will add "You should receive an SMS soon, please reply to it in order to answer" instead.

**Comment by ninsuo** [comment]
Done in #370
