### ISSUE TITLE
Trigger : Add a text field to store additional information on the trigger.

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#358]
When creating a DT Trigger, with multiple UL handling the response of their respective UL, it would be nice to be able to add some text to give update on the nature of the trigger.

Once saved, the trigger should transform URL into clickable links.

Update of this text field should be propagated to all connected users with a visual effect to notify the update

The dateTime of the last update should be displayed below the text field.

Ex: For example, the link to the google spreadsheet could be put there along with some updated information.
Otherwise, the link must be sent with a RedCall, which increase the cost

**Comment by ninsuo** [comment]
Required changes:
- add optional notes and notes last update fields on campaign entity and form
- add rendering of these notes on campaign status page
- add a modal allowing to edit notes on campaign status page
- add some javascript to make links inside notes clickable
- add the note on short polling and update it automatically
- add a visual effect to make the note update noticeable (play with the update date and add a button to acknowledge changes)
