### ISSUE TITLE
Structure have phone numbers that pass from a manager to another each week : we need to handle that

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#361]
Several structures (UL, DT) have phone number (téléphone d'astreinte) that is passed from one volunteer to another each week (or other period of time).
The one who has the telephone is responsible for a specific role (like handling redcall responses)

We currently can't handle this phone number.
If we replace the phone number of a person by this one, then when he's not on duty, he won't get trigger on his personnal phone.

The idea would be to list of fake volunteers that have a name, phone, email and that is attached to a Structure just like any volunteer. Except that these won't be affected by Pegass Synchro.

when searching for volunteer, a search option should allow to list all this kind of fake volunteers.

**Comment by ninsuo** [comment]
It is already possible to create "fake volunteers", closing this for now, pending for user feedbacks.
