### ISSUE TITLE
Create Trigger : create a page per trigger type (call, sms, email)

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#384]
On the welcome page
Something like this :
![image](https://user-images.githubusercontent.com/5695269/94441018-899c8c80-01a2-11eb-8b53-c2ee8e9e4423.png)

Each page is dedicated to one trigger type.

The rest of the functionalities should be common and evolve at the same pace.

This would make the Trigger form less complex and more maintanable

**Comment by ninsuo** [comment]
![Uploading Screenshot 2020-09-29 at 07.56.57.png…]()

**Comment by ninsuo** [comment]
<img width="930" alt="Screenshot 2020-09-29 at 07 56 57" src="https://user-images.githubusercontent.com/4152132/94518074-81d3fb00-0229-11eb-9240-ce3f94de52b1.png">

**Comment by dev-mansonthomas** [comment]
Noice :)
