### ISSUE TITLE
Add volunteer anonymization on "Edit volunteer" page

### ISSUE THREAD

**Issue by ninsuo** [redcall-io/app#398]
We need a way to entirely remove a volunteer when he asks us to not be disturbed anymore.
The "anonymize" feature is already live (but disabled) on the "Volunteer Space"
Link it to the Volunteer Management page
Also, send a message to the volunteer to tell him he has successfully been removed

**Comment by dev-mansonthomas** [comment]
The response to the person by SMS is : 

"Bonjour, nous avons pris en compte votre demande. Vous ne recevrez plus de message de notre part. Toutes nos excuses pour la gêne occasionnée. La Croix Rouge"


An email should also be sent to the structure of the user (user->structure) with the following text : 
Sujet: "RGPD - RedCall : Mettre à jour GAIA pour cette personne"

> Bonjour,
> 
> **Ce message doit être transféré au secrétaire de l'unité local ou au président.**
> 
> RedCall a reçu de la part de la personne ci-dessous un message indiquant qu'il n'est pas/plus bénévole à la Croix Rouge.
> La Croix Rouge se doit de respecter la [RGPD](https://www.cnil.fr/fr/rgpd-de-quoi-parle-t-on) et Il vous faut mettre à jour GAIA en ce sens.
> Du coté de RedCall, le nécessaire a été fait pour qu'il ne reçoive plus aucun déclenchement, et la personne a recu le message suivant : 
> "Bonjour, nous avons pris en compte votre demande. Vous ne recevrez plus de message de notre part. Toutes nos excuses pour la gêne occasionnée. La Croix Rouge"
>
> La personne concernée est : 
> 
> - Prénom : 
> - Nom : 
> - email : 
> - téléphone : 
> - NIVOL : 
> 
> le message reçu est : 
> ""

(for the received text message, if it's too complex, drop it)

**Comment by ninsuo** [comment]
done in #401
