### ISSUE TITLE
Auto disable volunteer that didn't respond on the last X call

### ISSUE THREAD

**Issue by dev-mansonthomas** [redcall-io/app#93]
* send an sms asking him if he wants to be kept in the call, if no answer in 24h or no, disable him

**Comment by ninsuo** [comment]
Nope it won't work.

- for example, in tonight's communication (asking for volunteer's availability next week), there are no "Unavailable" answer.  Thus, nobody reply.

- inbound answers are not free anymore (it's 0.005ct/answer), thus it's better to not force volunteers to answer.

**Comment by dev-mansonthomas** [comment]
Ok, so it would be nice to have a statistics module for each structure to explore how people respond (or not respond), to disable some.
see : 
https://github.com/redcall-io/app/issues/360
